# Generated by Django 4.2.1 on 2023-10-18 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Propiedades', '0007_municipio_alter_propiedad_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrendador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles', verbose_name='perfil')),
                ('ocupacion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('whatsapp', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=100)),
                ('preferencias_arrendatarios', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles', verbose_name='Foto')),
                ('universidad_actual', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('whatsapp', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=100)),
                ('preferencias_busqueda', models.CharField(max_length=500)),
                ('pasatiempos', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='perfiles.estudiante', verbose_name='Estudiante')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Propiedades.propiedad', verbose_name='Propiedad')),
            ],
        ),
    ]
