# Generated by Django 4.1.6 on 2023-10-30 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0010_alter_colonia_municipio_and_more'),
        ('perfiles', '0002_arrendador_usuario_estudiante_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='estudiante',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='perfiles.estudiante',
                verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='propiedad',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='Propiedades.propiedad',
                verbose_name='Propiedad'),
        ),
    ]
