# Generated by Django 4.2.1 on 2023-10-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles',
         '0003_alter_favorito_estudiante_alter_favorito_propiedad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
