# Generated by Django 4.1.5 on 2023-09-25 22:17

import Propiedades.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Propiedades", "0002_alter_propiedad_precio"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagenpropiedad",
            name="nombre",
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="propiedad",
            name="imagen",
            field=models.ImageField(
                default=2,
                upload_to=Propiedades.validators.directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpeg", "jpg"],
                        code="formato_invalido",
                        message="Sólo se permite formato PNG, JPEG, JPG.",
                    )
                ],
                verbose_name="Foto del Artículo",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="imagenpropiedad",
            name="imagen",
            field=models.ImageField(
                upload_to=Propiedades.validators.directory_path),
        ),
        migrations.AlterField(
            model_name="imagenpropiedad",
            name="propiedad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Propiedades.propiedad"
            ),
        ),
    ]
