# Generated by Django 4.1.5 on 2023-09-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Propiedades", "0003_imagenpropiedad_nombre_propiedad_imagen_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propiedad",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
