# Generated by Django 4.1.5 on 2023-09-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Propiedades", "0004_alter_propiedad_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="propiedad",
            name="nombre",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
