# Generated by Django 4.1.5 on 2023-09-25 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Propiedades", "0005_propiedad_nombre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagenpropiedad",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="propiedad",
            name="imagen",
        ),
        migrations.RemoveField(
            model_name="propiedad",
            name="nombre",
        ),
        migrations.AlterField(
            model_name="imagenpropiedad",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="imagenes", verbose_name="imagen"
            ),
        ),
        migrations.AlterField(
            model_name="imagenpropiedad",
            name="propiedad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Propiedades.propiedad",
                verbose_name="Propiedad",
            ),
        ),
        migrations.AlterField(
            model_name="propiedad",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
