# Generated by Django 4.2.1 on 2023-10-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0008_remove_propiedad_telefonoarrendador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
