# Generated by Django 4.1.6 on 2023-10-30 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_arrendador_usuario_estudiante_usuario'),
        ('Propiedades', '0009_alter_propiedad_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonia',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Propiedades.municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='imagenpropiedad',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Propiedades.propiedad', verbose_name='Propiedad'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='arrendador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.arrendador', verbose_name='Arrendador'),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_estudiante', to='perfiles.estudiante', verbose_name='Estudiante')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_propiedad', to='Propiedades.propiedad', verbose_name='Propiedad')),
            ],
        ),
    ]
