# Generated by Django 4.1.6 on 2023-11-13 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0004_delete_favorito'),
        ('Propiedades', '0011_resena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante_Interesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesado_estudiante', to='perfiles.estudiante', verbose_name='Estudiante')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesado_propiedad', to='Propiedades.propiedad', verbose_name='Propiedad')),
            ],
        ),
    ]
