# Generated by Django 4.1.5 on 2023-11-13 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("perfiles", "0004_delete_favorito"),
        ("Propiedades", "0013_remove_resena_estudiante_resena_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resena",
            name="user",
        ),
        migrations.AddField(
            model_name="resena",
            name="estudiante",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resenas_estudiante",
                to="perfiles.estudiante",
                verbose_name="Estudiante",
            ),
            preserve_default=False,
        ),
    ]
