# Generated by Django 4.1.6 on 2023-11-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0014_remove_resena_user_resena_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.IntegerField(default=0),
        ),
    ]
